### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by wheelq** [DefectDojo/Burp-Plugin#16]
This is loaded plugin:

![image](https://user-images.githubusercontent.com/1497172/58867880-20daf800-86b3-11e9-8077-6226ab5f4095.png)

And here is the Error log output:
```
DefectDojoPlugin.py", line 457, in sendIssue
    for i in range(lgt):
UnboundLocalError: local variable 'lgt' referenced before assignment
```

**Comment by adracea** [comment]
@wheelq I'll be looking into this later today .

**Comment by adracea** [comment]
Hey @wheelq , I can't seem to be able to replicate this issue , could you please provide me with more context on this issue ?

**Comment by wheelq** [comment]
1. I have downloaded latest version of the plugin from https://github.com/DefectDojo/Burp-Plugin
Below DefectDojo python file you can also see utils.py (also latest version)
And here is the output once isntalled and started:
![dd_burp_1](https://user-images.githubusercontent.com/1497172/59032909-49075a00-885f-11e9-80ca-f01cdba0fd5c.PNG)
2. Navigate to: Target->Site map-> choose hostname->Contents->Issues. Select one of the issues-> right click-> select: 'Send To Defect Dojo'
![dd_burp_3](https://user-images.githubusercontent.com/1497172/59032960-69371900-885f-11e9-9d85-baca3980b1ff.PNG)

3. Failure:
![dd_burp_2](https://user-images.githubusercontent.com/1497172/59033023-95eb3080-885f-11e9-9266-e1f54d64ba64.PNG)

And it is strange, as the plugin is able to grab engagements/tests etc...

**Comment by adracea** [comment]
Are those custom made issues ? If so , they might be missing certain fields but that error basically means that you have no selected issue , which is quite impossible ?

**Comment by wheelq** [comment]
I have used samples from here: https://github.com/DefectDojo/sample-scan-files

**Comment by wheelq** [comment]
Update: I have turned off some other plugins and now it works. Will start turning those on one by one to figure out which caused such issue. thanks!
