### ISSUE TITLE
Burp plugin installation not working

### ISSUE THREAD

**Issue by ukhichada** [DefectDojo/Burp-Plugin#19]
Hi Team,

I've followed the steps mentioned in 
https://github.com/DefectDojo/Burp-Plugin but getting error "Error connecting to DefectDojo , double check the URL"

I've enter DefectDojo : https:10.10.*.*:8083.

Please help to resolve this.

**Comment by mtesauro** [comment]
You can also ask your question on #defectdojo on OWASP's Slack - details at https://github.com/DefectDojo/django-DefectDojo#getting-involved

**Comment by dsever** [comment]
Just, hint, are you using self signed certs?

Dubravko

**Comment by adracea** [comment]
If the server is https and the certificate self-signed this is indeed an issue. We could add an option for bypassing it but I don't feel comfortable doing this as the server's certificate should be trusted.
I've tested with http://localhost:8080 and a trusted ssl cert for https://ip:443 and it's always worked.
