### ISSUE TITLE
Upgrade to use APIv2

### ISSUE THREAD

**Issue by adracea** [DefectDojo/Burp-Plugin#21]
Upgrade to use APIv2 in order to ensure proper compatibility with newer releases of Defect Dojo.

**Comment by madchap** [comment]
Hey @adracea 

I was wondering if you had the chance to take a look at this? 

Cheers,
fred

**Comment by adracea** [comment]
> Hey @adracea
> 
> I was wondering if you had the chance to take a look at this?
> 
> Cheers,
> fred

Hey @madchap  I was looking into this at some point but I do believe I may have lost the progress I had back then, I'll try to find some free time for it but if someone else can accomplish this sooner, I'd say it's up for taking .

**Comment by damiencarol** [comment]
@adracea @madchap  what's the goal of this issue?

**Comment by madchap** [comment]
It's not yet a PR but an issue. The Burp plugin does not work with apiv2 and apiv1 is now deprecated.

**Comment by ihebski** [comment]
@madchap  @adracea I have upgraded the plugin to support API v2, Could you please test it in your end https://github.com/ihebski/Burp-Plugin

I have submitted a pull request for this issue.

Thanks

**Comment by madchap** [comment]
I'll give it a shot soon :+1: Thanks for that contribution!
