### ISSUE TITLE
Burp Plugin

### ISSUE THREAD

**Issue by sangamthakur-sec** [DefectDojo/Burp-Plugin#23]
Using Burp suite pro with defect dojo plugin. I am not able to retrieve the product name even though the product type is already created via UI.

Get the following error. Sharing some of the logs
[error_log.txt](https://github.com/DefectDojo/Burp-Plugin/files/6277068/error_log.txt)

Looking forward to solutions.

**Comment by 0xAmal** [comment]
is there any update on this

**Comment by mtesauro** [comment]
Archiving this repo - The Burp plug-in depends on jython, which is now outdated and it has been a year since a formal release.
