### ISSUE TITLE
Error connecting to DefectDojo certificate verify failed

### ISSUE THREAD

**Issue by rjutin** [DefectDojo/Burp-Plugin#28]
![image](https://github.com/DefectDojo/Burp-Plugin/assets/106729548/73d3166b-5060-424b-97ca-ee940b5930f2)
Hello I have error with connection to my defect-dojo in output log i see:

Error: [Errno 1] certificate verify failed (java.security.cert.CertificateException: certificate verify failed)

my https certificate is self signed.

**Comment by mtesauro** [comment]
Archiving this repo - The Burp plug-in depends on jython, which is now outdated and it has been a year since a formal release.
